2025-03-10 12:26:42,088 [INFO] USER:velma_saivarshitha handlers.py:106:syndicate LOG: Configuration used: C:\Users\velma_saivarshitha\Desktop\Lamda-Project\.syndicate-config-dev
2025-03-10 12:26:44,377 [WARNING] USER:velma_saivarshitha __init__.py:190:initialize_project_state LOG: [93mConfig is set and generated but project state does not exist, seems that you've come from the previous version.[0m
2025-03-10 12:26:44,378 [WARNING] USER:velma_saivarshitha __init__.py:193:initialize_project_state LOG: [93mGenerating project state file (.syndicate) from the existing structure...[0m
2025-03-10 12:26:44,397 [INFO] USER:velma_saivarshitha processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-10 12:26:46,150 [INFO] USER:velma_saivarshitha sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-10 12:26:46,151 [INFO] USER:velma_saivarshitha helper.py:658:check_lambda_name LOG: Validating lambda name: 'hello_world'
2025-03-10 12:26:46,151 [INFO] USER:velma_saivarshitha helper.py:673:check_lambda_name LOG: Lambda name: 'hello_world' passed the validation
2025-03-10 12:26:46,151 [INFO] USER:velma_saivarshitha helper.py:647:resolve_project_path LOG: Parameter: 'project_path' wasn't specified. Getting automatically
2025-03-10 12:26:46,152 [INFO] USER:velma_saivarshitha helper.py:651:resolve_project_path LOG: Path: 'C:/Users/velma_saivarshitha/Desktop/Lamda-Project' was assigned to the parameter: 'project_path'
2025-03-10 12:26:46,153 [INFO] USER:velma_saivarshitha generate.py:116:lambda_function LOG: Lambda names: ('hello_world',)
2025-03-10 12:26:46,153 [INFO] USER:velma_saivarshitha generate.py:117:lambda_function LOG: Runtime: java
2025-03-10 12:26:46,154 [INFO] USER:velma_saivarshitha generate.py:118:lambda_function LOG: Project path: C:/Users/velma_saivarshitha/Desktop/Lamda-Project
2025-03-10 12:26:46,155 [INFO] USER:velma_saivarshitha project.py:90:_generate_java_project_hierarchy LOG: Generating pom inside C:/Users/velma_saivarshitha/Desktop/Lamda-Project
2025-03-10 12:26:46,157 [INFO] USER:velma_saivarshitha project.py:95:_generate_java_project_hierarchy LOG: Pom file was generated by path: C:/Users/velma_saivarshitha/Desktop/Lamda-Project\pom.xml
2025-03-10 12:26:46,161 [WARNING] USER:velma_saivarshitha lambda_function.py:358:_generate_java_lambdas LOG: The project root 'deployment_resources.json' file is absent. Creating...
2025-03-10 12:26:46,162 [INFO] USER:velma_saivarshitha lambda_function.py:374:_generate_java_lambdas LOG: Lambda hello_world created
2025-03-10 12:26:46,163 [INFO] USER:velma_saivarshitha lambda_function.py:169:generate_lambda_function LOG: Lambda hello_world has been successfully added to the project.
2025-03-10 12:26:46,164 [INFO] USER:velma_saivarshitha helper.py:330:timed LOG: Stage lambda_function, elapsed time: 0:00:00.011152
2025-03-10 12:31:29,527 [INFO] USER:velma_saivarshitha handlers.py:106:syndicate LOG: Configuration used: C:\Users\velma_saivarshitha\Desktop\Lamda-Project\.syndicate-config-dev
2025-03-10 12:31:31,777 [INFO] USER:velma_saivarshitha processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-10 12:31:33,281 [INFO] USER:velma_saivarshitha project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-10 12:31:33,282 [INFO] USER:velma_saivarshitha project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-10 12:31:33,691 [INFO] USER:velma_saivarshitha sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-10 12:38:31,098 [INFO] USER:velma_saivarshitha handlers.py:106:syndicate LOG: Configuration used: C:\Users\velma_saivarshitha\Desktop\Lamda-Project\.syndicate-config-dev
2025-03-10 12:38:33,365 [INFO] USER:velma_saivarshitha processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-10 12:38:34,880 [INFO] USER:velma_saivarshitha project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-10 12:38:34,880 [INFO] USER:velma_saivarshitha project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-10 12:38:35,373 [INFO] USER:velma_saivarshitha sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-10 12:38:35,374 [INFO] USER:velma_saivarshitha helper.py:658:check_lambda_name LOG: Validating lambda name: 'hello_word'
2025-03-10 12:38:35,374 [INFO] USER:velma_saivarshitha helper.py:673:check_lambda_name LOG: Lambda name: 'hello_word' passed the validation
2025-03-10 12:38:35,374 [INFO] USER:velma_saivarshitha helper.py:647:resolve_project_path LOG: Parameter: 'project_path' wasn't specified. Getting automatically
2025-03-10 12:38:35,375 [INFO] USER:velma_saivarshitha helper.py:651:resolve_project_path LOG: Path: 'C:/Users/velma_saivarshitha/Desktop/Lamda-Project' was assigned to the parameter: 'project_path'
2025-03-10 12:38:35,376 [INFO] USER:velma_saivarshitha generate.py:116:lambda_function LOG: Lambda names: ('hello_word',)
2025-03-10 12:38:35,376 [INFO] USER:velma_saivarshitha generate.py:117:lambda_function LOG: Runtime: java
2025-03-10 12:38:35,376 [INFO] USER:velma_saivarshitha generate.py:118:lambda_function LOG: Project path: C:/Users/velma_saivarshitha/Desktop/Lamda-Project
2025-03-10 12:38:35,389 [INFO] USER:velma_saivarshitha project.py:97:_generate_java_project_hierarchy LOG: Pom file inside C:/Users/velma_saivarshitha/Desktop/Lamda-Project already exists
2025-03-10 12:38:35,393 [INFO] USER:velma_saivarshitha lambda_function.py:374:_generate_java_lambdas LOG: Lambda hello_word created
2025-03-10 12:38:35,404 [INFO] USER:velma_saivarshitha lambda_function.py:169:generate_lambda_function LOG: Lambda hello_word has been successfully added to the project.
2025-03-10 12:38:35,404 [INFO] USER:velma_saivarshitha helper.py:330:timed LOG: Stage lambda_function, elapsed time: 0:00:00.028775
